=== OliverZott/docs/markup languages/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://mysite.com/student"
           xmlns="https://mysite.com/student">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:int" />
<!--                            <xs:element name="lastname" type="xs:string" />-->
                            <xs:element name="age" type="xs:int" />
                            <xs:element name="courses">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element
                                            name="course"
                                            type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OliverZott/docs/markup languages/student.xml
<?xml-stylesheet type="text/xsl" href="student.xsd"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="student.xsd"> <!-- xsi:schemaLocation="http://www.example.com student.xsd" -->
  <!--1 or more repetitions:-->
  <student>
    <firstname>Olli</firstname>
    <lastname>Zott</lastname>
    <age>40</age>
    <courses>
      <!--1 or more repetitions:-->
      <course>math</course>
      <course>physics</course>
    </courses>
  </student>
</students>
